### ISSUE TITLE
How to set data in checkboxCombo form?

### ISSUE THREAD

**Issue by niesuch** [cesaredamico/extUxCheckboxCombo#1]
I can't check checkboxes from array, I want check 1,2,3 and 4 checkbox on my checkbox list. Can you help me?

**Comment by cesaredamico** [comment]
Sorry, this is not my code (see [README.md](https://github.com/cesaredamico/extUxCheckboxCombo/blob/master/README.md)) and I've not used it in years. It was originally hosted on Google Code, and when the news came out that that service would have been closed, I just opened this repository in order to save this tiny package.
